language: python
python:
- '3.7'
env:
  matrix:
  - DJANGO=3.0.3
addons:
  ssh_known_hosts:
  - 95.217.134.247
  - 95.217.134.247:8080
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- export PYTHONPATH="/home/travis/build/softalaproject/fridge_manager"
install:
- pip3 install -r requirements.txt
- pip3 install django==$DJANGO --quiet
- pip3 install psycopg2 --quiet
script:
- python3 restmanager/manage.py migrate
- python3 restmanager/manage.py test frontend
after_success: '[[ $TRAVIS_BRANCH == "dev2" && $TRAVIS_PULL_REQUEST == "false" ]] && .travis/deploy.sh'

