language: python
python:
  - "3.6"     
  - "3.7"      # current default Python on Travis CI
before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
after_success: "[[ $TRAVIS_BRANCH == \"dev\" && $TRAVIS_PULL_REQUEST == \"false\" ]] && .travis/deploy.sh"
