language: python
python:
  - "3.6"     
  - "3.7"      # current default Python on Travis CI
before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out id_rsa -d
  - pip3 install -r requirements.txt
  - pip3 install pylint pylint-django
after_success: "[[ $TRAVIS_BRANCH == \"master\" && $TRAVIS_PULL_REQUEST == \"false\" ]] && .travis/deploy.sh"