language: python
python:
  - "3.7"      # current default Python on Travis CI

env:
  - DJANGO=3.0.3

before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
#  - export DJANGO_SETTINGS_MODULE=fridge_manager.restmanager.restmanager.settings
  - export PYTHONPATH="/home/travis/build/softalaproject/fridge_manager"

install:
  - pip3 install -r requirements.txt
  - pip3 install django==$DJANGO --quiet
  - pip3 install psycopg2 --quiet

script:
  - pwd
  - python restmanager/manage.py migrate
  - python restmanager/manage.py runserver
  - python restmanager/manage.py test functional_tests

after_success: "[[ $TRAVIS_BRANCH == \"feature/travis-server\" && $TRAVIS_PULL_REQUEST == \"false\" ]] && .travis/deploy.sh"
